# Generated by Django 4.2 on 2023-12-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_album_description_element_delete_elements_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Amounts",
            new_name="Amount",
        ),
        migrations.AddField(
            model_name="description",
            name="main_photo",
            field=models.ImageField(default=" ", upload_to="main/"),
            preserve_default=False,
        ),
    ]
