# Generated by Django 4.2 on 2023-12-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="purpose",
            field=models.CharField(max_length=20),
        ),
    ]
