# Generated by Django 5.0 on 2025-02-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0008_delete_amount_remove_album_element_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="parent_element",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="portfolio.element",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="type",
            field=models.CharField(
                choices=[("ser", "Серии фотографий"), ("rep", "Репортаж")],
                default="ser",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="description",
            name="page",
            field=models.CharField(
                choices=[("main", "Главная страница"), ("abme", "Страница обо мне")],
                max_length=4,
                unique=True,
            ),
        ),
    ]
