# Generated by Django 5.0 on 2025-02-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0010_image_parent_element_alter_album_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="element",
            name="photos",
        ),
        migrations.AddField(
            model_name="element",
            name="grad_color",
            field=models.CharField(
                blank=True,
                default="rgba(35,59,52,0.7)",
                help_text="Цвет градиента, например, rgba(35,59,52,0.7)",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="text_color",
            field=models.CharField(
                blank=True,
                default="#000000",
                help_text="Цвет текста в формате HEX (например, #58b999)",
                max_length=7,
                null=True,
            ),
        ),
    ]
