# Generated by Django 5.0 on 2025-02-12 18:23

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0012_album_grad_color_album_text_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="text_color",
            field=colorfield.fields.ColorField(
                default="#000000",
                help_text="Выберите цвет текста",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="text_color",
            field=colorfield.fields.ColorField(
                default="#000000",
                help_text="Выберите цвет текста",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
    ]
