# Generated by Django 4.2 on 2023-12-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='ser', max_length=3)),
                ('image', models.ImageField(upload_to='screensaver/')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('style_number', models.PositiveIntegerField(default=1)),
                ('element_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('page', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='ser', max_length=3)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('style_number', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.album')),
            ],
        ),
        migrations.DeleteModel(
            name='Elements',
        ),
        migrations.RemoveField(
            model_name='image',
            name='collection',
        ),
        migrations.AlterField(
            model_name='amounts',
            name='reports_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amounts',
            name='series_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SerieElement',
        ),
        migrations.AddField(
            model_name='element',
            name='images',
            field=models.ManyToManyField(to='portfolio.image'),
        ),
    ]
