# Generated by Django 4.2 on 2023-12-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_amounts_amount_description_main_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('vk_url', models.URLField(blank=True, null=True)),
                ('is_vk_answer', models.BooleanField(blank=True, default=False, null=True)),
                ('message', models.TextField()),
                ('purpose', models.CharField(choices=[('', 'Выберите тему сообщения'), ('question', 'Задать вопрос'), ('photo', 'Заказать съёмку'), ('opinion', 'Спросить совета'), ('other', 'Другое')], max_length=20)),
                ('get_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
