# Generated by Django 4.2 on 2023-12-17 08:39

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('portfolio', '0005_alter_order_purpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='images',
            new_name='photos',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
